TCRC/Models/Admin/Member.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TCRC.Models.Admin
{
    public class Member
    {
        public int TcrcID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Agency { get; set; }
        public DateTime TcrcExpiration { get; set; }
        public DateTime SotExpiration { get; set; }
    }
}

TCRC/Models/Admin/MemberViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using TCRC.Models.Member;

namespace TCRC.Models.Admin
{
    public sealed class MemberViewModel
    {
        public int TcrcNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string AgencyName { get; set; }
        public DateTime TcrcExpirationDate { get; set; }
        public DateTime? SotExpirationDate { get; set; }
    }
}

TCRC/Models/Admin/ProcessClaimViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;
using TCRC.Models.FileClaim;

namespace TCRC.Models.Admin
{
    public class ProcessClaimViewModel : ClaimFormViewModel
    {
        public static IList<SelectListItem> ClaimStatusTypes
        {
            get
            {
                IList<SelectListItem> statusTypes = new List<SelectListItem>();
                statusTypes.Add(new SelectListItem() { Text = "", Value = "", Selected = true });
                statusTypes.Add(new SelectListItem() { Text = "Abandoned", Value = "2" });
                statusTypes.Add(new SelectListItem() { Text = "Appeal Denied", Value = "7" });
                statusTypes.Add(new SelectListItem() { Text = "Approved, Not Paid", Value = "4" });
                statusTypes.Add(new SelectListItem() { Text = "Approved, Paid", Value = "3" });
                statusTypes.Add(new SelectListItem() { Text = "Check Bounced", Value = "11" });
                statusTypes.Add(new SelectListItem() { Text = "Check Cleared", Value = "10" });
                statusTypes.Add(new SelectListItem() { Text = "Check Received", Value = "9" });
                statusTypes.Add(new SelectListItem() { Text = "Denied", Value = "5" });
                statusTypes.Add(new SelectListItem() { Text = "Fee Refunded", Value = "8" });
                statusTypes.Add(new SelectListItem() { Text = "In Appeal", Value = "6" });
                statusTypes.Add(new SelectListItem() { Text = "In Process", Value = "1" });
                statusTypes.Add(new SelectListItem() { Text = "In Process Admin", Value = "12" });

                return statusTypes;
            }
        }

        [Display(Name = "Claim Status Letter")]
        public string EmailText { get; set; }

        [Display(Name = "Do Not Send Letter")]
        public bool DoNotSendLetter { get; set; }

        [Display(Name = "Claim Check Number")]
        public int? ApprovedCheckNumber { get; set; }

        [Display(Name = "Claim Check Amount")]
        public decimal? ApprovedCheckAmount { get; set; }

        [Display(Name = "Claim Check Date")]
        public DateTime? ApprovedCheckDate { get; set; }

        [Display(Name = "Fee Refund Amount")]
        public decimal? FeeRefundAmount { get; set; }

        [Display(Name = "Check Number")]
        public int? ReceivedCheckNumber { get; set; }

        [Display(Name = "Check Amount")]
        public decimal? ReceivedCheckAmount { get; set; }

        [Display(Name = "Check Date")]
        public DateTime? ReceivedCheckDate { get; set; }

        [Display(Name = "Check Cleared Date")]
        public DateTime? ReceivedCheckClearedDate { get; set; }

        [Display(Name = "Check Bounced Date")]
        public DateTime? ReceivedCheckBouncedDate { get; set; }

        public string Notes { get; set; }
    }
}

TCRC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using TCRC.Domain.DTOs;
using TCRC.Models.Admin;
using TCRC.Models.FileClaim;
using TCRC.Models.Member;
using TCRC.Helpers;
using TCRC.BusinessLogic.Services;
using AutoMapper;
using WebMatrix.WebData;

namespace TCRC.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class AdminController : BaseController
    {
        #region Members
        private readonly IAdminService adminService;
        private readonly IClaimService claimService;
        private readonly IMemberService memberService;
        #endregion

        #region Members
        /// <summary>
        /// Admin controller constructor
        /// </summary>
        /// <param name="adminService">The admin service</param>
        /// <param name="claimService">The claim service</param>
        /// <param name="memberService">The member service</param>
        public AdminController(IAdminService adminService, IClaimService claimService, IMemberService memberService)
        {
            this.adminService = adminService;
            this.claimService = claimService;
            this.memberService = memberService;
        }

        /// <summary>
        /// View Sot import
        /// </summary>
        public ActionResult ImportSot()
        {
            return View();
        }

        /// <summary>
        /// Import sellers of travel
        /// </summary>
        /// <param name="file">The file to import</param>
        /// <returns>Returns the view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ImportSot(HttpPostedFileBase file)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    //todo: validate file format is csv
                    StringBuilder fileName = new StringBuilder(DateTime.Now.Ticks.ToString()).Append("_")
                        .Append(Path.GetFileNameWithoutExtension(file.FileName)).Append("_")
                        .Append(DateTime.Now.ToString("yyyyMMdd"))
                        .Append(Path.GetExtension(file.FileName));

                    Directory.CreateDirectory(Server.MapPath("~/App_Data/Uploads/SotImport"));

                    var filePath = Path.Combine(Server.MapPath("~/App_Data/Uploads/SotImport"), fileName.ToString());
                    file.SaveAs(filePath);
                    adminService.ImportSots(filePath);
                }
                //todo: return message
            }
            catch (Exception e)
            {
                //todo: handle exception
            }
            return View();
        }

        /// <summary>
        /// View reports
        /// </summary>
        public ActionResult Reports()
        {
            return View();
        }

        /// <summary>
        /// View users
        /// </summary>
        public ActionResult Users()
        {
            //var users = adminService.GetUsers();
            UsersViewModel model = new UsersViewModel();
            List<UserProfileDTO> userProfiles = adminService.GetUsers().ToList();
            model.Users = Mapper.Map<List<UserProfileDTO>, List<UserProfileViewModel>>(userProfiles);

            return View(model);
        }

        /// <summary>
        /// View member search
        /// </summary>
        /// <returns></returns>
        public ActionResult SearchMembers()
        {
            return View();
        }

        /// <summary>
        /// Search members
        /// </summary>
        /// <param name="model">The member search view model</param>
        /// <returns>Returns the member search view model</returns>
        [HttpPost]
        public ActionResult SearchMembers(MemberSearchViewModel model)
        {
            MemberSearchDTO memberSearch = Mapper.Map<MemberSearchViewModel, MemberSearchDTO>(model);
            List<MemberDTO> members = adminService.SearchMembers(memberSearch).ToList();
            
            model.Members = Mapper.Map<List<MemberDTO>, List<MemberViewModel>>(members);
            return View(model);
        }

        /// <summary>
        /// View claim search
        /// </summary>
        public ActionResult SearchClaim()
        {
            return View();
        }

        /// <summary>
        /// Search claims
        /// </summary>
        /// <param name="model">The search claim view model</param>
        /// <returns>Returns the search claim view model</returns>
        [HttpPost]
        public ActionResult SearchClaim(SearchClaimViewModel model)
        {
            SearchClaimDTO searchClaim = Mapper.Map<SearchClaimViewModel, SearchClaimDTO>(model);
            var claims = claimService.SearchClaims(searchClaim);
            model.Claims = claims;
            
            return View(model);
        }

        /// <summary>
        /// View claim details
        /// </summary>
        /// <param name="claimID">The claim id</param>
        /// <returns>Returns the process claim view model</returns>
        public ActionResult Claim(int claimID)
        {
            ClaimFormDTO processClaim = claimService.GetClaimByID(claimID);
            ProcessClaimViewModel model = Mapper.Map<ClaimFormDTO, ProcessClaimViewModel>(processClaim);

            return View(model);
        }

        /// <summary>
        /// Gets the claim status type
        /// </summary>
        /// <param name="claimId">The claim id</param>
        /// <param name="claimStatusTypeId">The claims status type id</param>
        /// <param name="claimant">The claimant</param>
        /// <param name="address">The address</param>
        /// <param name="city">The city</param>
        /// <param name="state">The state</param>
        /// <param name="zip">The zip code</param>
        /// <returns>Returns claim status type json</returns>
        public JsonResult GetClaimStatusType(int claimId, int claimStatusTypeId, string claimant, string address, string city, string state, string zip)
        {
            var claimStatusType = claimService.GetClaimStatusType(claimId, claimStatusTypeId, claimant, address, city, state, zip);

            return new JsonResult() { Data = claimStatusType, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
        }

        /// <summary>
        /// View process claim
        /// </summary>
        public ActionResult ProcessClaim()
        {
            return View();
        }

        /// <summary>
        /// Update a claim
        /// </summary>
        /// <param name="model">The claim view model</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultipleButton(Name = "action", Argument = "update")]
        public ActionResult UpdateClaim(ProcessClaimViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ClaimFormDTO claimForm = Mapper.Map<ClaimFormViewModel, ClaimFormDTO>(model);
                    claimService.UpdateClaim(claimForm, WebSecurity.CurrentUserId);
                }
                catch (Exception e)
                {
                    //todo: review the model error message
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if problem persists contact the system administrator.");
                    return RedirectToAction("Index", "Error");
                }

                return RedirectToAction("Claim", new { claimID = model.ClaimID });
            }
            else
            {
                return View(model);
            }
        }

        /// <summary>
        /// Process a claim
        /// </summary>
        /// <param name="model">The process claim view model</param>
        /// <returns>Return the process claim view model</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [MultipleButton(Name = "action", Argument = "process")]
        public ActionResult ProcessClaim(ProcessClaimViewModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    ProcessClaimDTO claimForm = Mapper.Map<ProcessClaimViewModel, ProcessClaimDTO>(model);
                    claimService.ProcessClaim(claimForm, WebSecurity.CurrentUserId);
                }
                catch (Exception e)
                {
                    //todo: review the model error message
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if problem persists contact the system administrator.");
                    return RedirectToAction("Index", "Error");
                }

                return RedirectToAction("Claim", new { claimID = model.ClaimID });
            }
            else
            {
                return View(model);
            }
        }

        /// <summary>
        /// View a member
        /// </summary>
        /// <param name="tcrcID">The tcrc id</param>
        /// <returns>Returns a member view model</returns>
        public ActionResult Member(string tcrcID)
        {
            MemberRegisterDTO member = memberService.GetMemberByID(tcrcID);
            ProcessMemberViewModel model = Mapper.Map<MemberRegisterDTO, ProcessMemberViewModel>(member);

            List<MemberCheckHistoryDTO> checkHistories = memberService.GetMemberCheckHistories(int.Parse(tcrcID)).ToList();
            model.MemberCheckHistories = Mapper.Map<List<MemberCheckHistoryDTO>, List<MemberCheckHistory>>(checkHistories);

            return View(model);
        }
        #endregion
    }
}

TCRC/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebMatrix.WebData;
using TCRC.BusinessLogic.Services;
using TCRC.Domain.DTOs;
using TCRC.Helpers;
using TCRC.Models;
using TCRC.Models.Member;
using AutoMapper;

namespace TCRC.Controllers
{
    public class MemberController : BaseController
    {
        #region Members
        private readonly IMemberService memberService;
        #endregion

        #region Methods
        /// <summary>
        /// Member controller constructor
        /// </summary>
        /// <param name="service">The member service</param>
        public MemberController(IMemberService service)
        {
            this.memberService = service;
        }

        /// <summary>
        /// View register member
        /// </summary>
        public ActionResult Register()
        {
            return View();
        }

        /// <summary>
        /// Register a member
        /// </summary>
        /// <param name="model">The member register view model</param>
        /// <returns>Returns the register view model</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                MemberRegisterDTO member = Mapper.Map<RegisterViewModel, MemberRegisterDTO>(model);
                memberService.CreateMember(member);

                //add user authentication thru SimpleMembership model
                WebSecurityInitializer.Instance.EnsureInitialize();
                WebSecurity.CreateUserAndAccount(model.UserName, model.Password, propertyValues: new
                {
                    FirstName = model.BusinessContacts[0].FirstName,
                    LastName = model.BusinessContacts[0].LastName,
                    Email = model.BusinessContacts[0].EmailAddress
                });

                return View("RegistrationSubmitted", model);
            }
            else
            {
                return View(model);
            }
        }

        /// <summary>
        /// Renew a membership
        /// </summary>
        /// <param name="model">The register view model</param>
        /// <returns>Returns the register view model</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RenewMembership(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                MemberRegisterDTO member = Mapper.Map<RegisterViewModel, MemberRegisterDTO>(model);
                memberService.RenewMembership(member);

                return View();
            }
            else
            {
                return View(model);
            }
        }

        /// <summary>
        /// Gets member details
        /// </summary>
        /// <returns>Returns member details view model</returns>
        [Authorize]
        public ActionResult Details()
        {
            string userName = User.Identity.Name;
            DetailsViewModel detailsViewModel = new DetailsViewModel();

            if (!String.IsNullOrEmpty(userName))
            {
                MemberDetailDTO memberDetail = memberService.GetMemberDetailsByUserName(userName);
                detailsViewModel = Mapper.Map<MemberDetailDTO, DetailsViewModel>(memberDetail);
            }

            return View(detailsViewModel);
        }

        /// <summary>
        /// View change password
        /// </summary>
        public ActionResult ChangePassword()
        {
            return View();
        }

        /// <summary>
        /// Renew a membership
        /// </summary>
        /// <returns>Returns a register view model</returns>
        public ActionResult RenewMembership()
        {
            //todo: add redirect for admin or member without a history
            string userName = User.Identity.Name;
            MemberRegisterDTO member = memberService.GetMemberByUserName(userName);
            RegisterViewModel model = Mapper.Map<MemberRegisterDTO, RegisterViewModel>(member);
            return View(model);
        }
        #endregion
    }
}

TCRC/Views/Admin/Claim.cshtml
@model TCRC.Models.Admin.ProcessClaimViewModel

@using (Html.BeginForm("", "Admin", FormMethod.Post, new { id = "admin-claim-form", @class = "pure-form pure-form-stacked" }))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(m => m.ClaimID)
    @Html.HiddenFor(m => m.BusinessAddressId)
    @Html.HiddenFor(m => m.TcrcId)

    Html.RenderPartial("_ClaimantInfo", Model);
    <br />
    Html.RenderPartial("_PaymentProof", Model);
    <br />
    Html.RenderPartial("~/Views/FileClaim/_ServicesPurchased.cshtml", Model);
    <br />
    Html.RenderPartial("~/Views/FileClaim/_TravelAgency.cshtml", Model);
    <br />
    Html.RenderPartial("~/Views/FileClaim/_ClaimDetails.cshtml", Model);
    <br />
    Html.RenderPartial("_Documents", Model);
    <br />
    Html.RenderPartial("~/Views/FileClaim/_InsuranceInfo.cshtml", Model);
    <br />
    Html.RenderPartial("~/Views/FileClaim/_Reimbursement.cshtml", Model);
    <br />
    Html.RenderPartial("_ClaimStatus", Model);
    <div style="padding: 10px 0 30px 0; width: 100%;">
        <input type="submit" id="btnUpdate" name="action:update" class="pure-button pure-button-primary" value="Update Claim" />
        <input type="submit" id="btnSubmit" name="action:process" class="pure-button pure-button-primary" value="Process Claim" />
    </div>
    Html.RenderPartial("_History", Model);
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/mask")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/jquery.xfields.js")
    @Scripts.Render("~/Scripts/kendo.all.min.js")
    @Scripts.Render("~/Scripts/tcrc.claim.js")
    @Scripts.Render("~/Scripts/tcrc.claim-admin.js")
}

TCRC/Views/Admin/ImportSot.cshtml
<h2>Import Sellers of Travel</h2>

@using (Html.BeginForm("ImportSot", "Admin", FormMethod.Post, new { @class = "pure-form pure-form-stacked", enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken();

    <fieldset>
        <legend>Import</legend>
        <div class="pure-g">
            <div class="pure-u-1">
                <label>Step 1 Choose a csv file to import</label>
                <input type="file" name="file" />
            </div>
            <div class="pure-u-1" style="padding-top: 20px;">
                <label>Step 2 Import the data</label>
                <input type="submit" value="Import" />
            </div>
        </div>
    </fieldset>
}

TCRC/Views/Admin/SearchClaim.cshtml
@model TCRC.Models.Admin.SearchClaimViewModel

<h2>Search Claim</h2>

@using (Html.BeginForm("SearchClaim", "Admin", FormMethod.Post, new { @class = "pure-form pure-form-stacked" }))
{
    <fieldset>
        <legend></legend>

        <div class="pure-g">
  
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.TCRCNumber)
                @Html.TextBoxFor(m => m.TCRCNumber, new { Maxlength = "20" })
            </div>
   
            <div class="pure-u-1-2">
                 @Html.LabelFor(m => m.AgencyName )
                @Html.TextBoxFor(m => m.AgencyName , new { Maxlength = "20" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.ClaimNumber )
                @Html.TextBoxFor(m => m.ClaimNumber , new { Maxlength = "20" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.ZipCode )
                @Html.TextBoxFor(m => m.ZipCode , new { Maxlength = "5" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.ClaimantName )
                @Html.TextBoxFor(m => m.ClaimantName , new { Maxlength = "20" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.ClaimDate )
                @Html.TextBoxFor(m => m.ClaimDate , new { @class = "datepicker" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.City )
                @Html.TextBoxFor(m => m.City , new { Maxlength = "20" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.ClaimStatus)
                @Html.DropDownListFor(m => m.ClaimStatus, TCRC.Models.Admin.SearchClaimViewModel.ClaimStatuses)
            </div>
            <div class="pure-u-1-1">
                <input type="submit" class="pure-button pure-button-primary" value="Search"  />&nbsp;&nbsp;&nbsp;&nbsp;
                <input type="submit" class="pure-button pure-button-primary" value="Clear"  />
            </div>

            <div class="pure-u-1">
                @if (Model != null)
                {
                    <table id="tbl-search-results" class="pure-table pure-table-striped">
                        <thead>
                            <tr>
                                <th>Claim Number</th>
                                <th>Claimant</th>
                                <th>Claim Date</th>
                                <th>Agency</th>
                                <th>Status</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var claim in Model.Claims)
                            {
                                <tr>
                                    @*<td>@claim.ClaimNumber</td>*@
                                    <td>@Html.ActionLink(claim.ClaimNumber.ToString(), "Claim", "Admin", new { claimID = claim.ClaimNumber }, null)</td>
                                    <td>@claim.FirstName @claim.LastName</td>
                                    <td>@claim.ClaimDate</td>
                                    <td>@claim.AgencyName</td>
                                    <td>@claim.Status</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                }
            </div>
        </div>
    </fieldset>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/tcrc.admin.claim-search.js")
}

TCRC/Views/Admin/SearchMembers.cshtml
@model TCRC.Models.Admin.MemberSearchViewModel


<h2>Administration - Search Participants</h2>

@using (Html.BeginForm("SearchMembers", "Admin", FormMethod.Post, new { @class = "pure-form pure-form-stacked" }))
{
    <fieldset>
        <legend></legend>
        <p>
            Enter your search criteria in one or more fields and click Search.
        </p>
        <div class="pure-g">
            <div class="pure-u-1-2">

                @Html.LabelFor(m => m.TCRCNumber, "TCRC Number")
                @Html.TextBoxFor(m => m.TCRCNumber, new { @class = "numbersOnly", maxlength = "20" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.AgencyName, "TCRC Agency Name")
                @Html.TextBoxFor(m => m.AgencyName, new { Maxlength = "20" })
            </div>
            <div class="pure-u-1-2">

                @Html.LabelFor(m => m.ParticipantFirstName, "Participant First Name")
                @Html.TextBoxFor(m => m.ParticipantFirstName, new { maxlength = "20" })
            </div>
            <div class="pure-u-1-2">
                @Html.LabelFor(m => m.ParticipantLastName, "Participant Last Name")
                @Html.TextBoxFor(m => m.ParticipantLastName, new { Maxlength = "20" })
            </div>
            <div class="pure-u-1">
                @Html.CheckBoxFor(m => m.IsParticipantPaymentProcessIncomplete)
                @Html.LabelFor(m => m.IsParticipantPaymentProcessIncomplete)
            </div>
        </div>

        <div class="pure-u-1-1">
            <input type="submit" class="pure-button pure-button-primary" value="Search" />&nbsp;&nbsp;&nbsp;&nbsp;
            <input type="submit" class="pure-button pure-button-primary" value="Clear" />
        </div>

        <div class="pure-u-1">
            @if (Model != null)
            {
                <table id="tbl-search-results" class="pure-table pure-table-striped">
                    <thead>
                        <tr>
                            <th>TCRC Number</th>
                            <th>Participant</th>
                            <th>Agency</th>
                            <th>TCRC Expiration</th>
                            <th>SOT Expiration</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var member in Model.Members)
                        {
                            <tr>
                                @*<td>@member.TcrcNumber</td>*@
                                <td>@Html.ActionLink(member.TcrcNumber.ToString(), "Member", "Admin", new { tcrcID = member.TcrcNumber }, null)</td>
                                <td>@member.FirstName @member.LastName</td>
                                <td>@member.AgencyName</td>
                                <td>@member.TcrcExpirationDate</td>
                                <td>@member.SotExpirationDate</td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </fieldset>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/tcrc.admin.member-search.js")
}

TCRC/Views/Admin/_Documents.cshtml
@model TCRC.Models.FileClaim.ClaimFormViewModel

<fieldset>
    <legend>Documents</legend>
    <p>
        You must provide a copy of those documents that set forth the travel services purchased, such as airline tickets, itinerary, 
        invoice or other agreements that support your claim. Input the title of the document and a description of its contents.
    </p>
    @{
        var cnt = 0;
        while (cnt < Model.ClaimDocuments.Count)
        {
            @Html.HiddenFor(m => m.ClaimDocuments[cnt].ClaimDocumentId)
            @Html.HiddenFor(m => m.ClaimDocuments[cnt].ClaimId)
            <div class="pure-g FormElementGroupDocuments">
                <div class="pure-u-1-3">
                    @Html.LabelFor(m => m.ClaimDocuments[cnt].Name, new { @class = "req" })
                    @Html.TextBoxFor(m => m.ClaimDocuments[cnt].Name, new { maxlength = "100", required = "required" })
                    @Html.ValidationMessageFor(m => m.ClaimDocuments[cnt].Name)
                </div>
                <div class="pure-u-2-3">
                    @Html.LabelFor(m => m.ClaimDocuments[cnt].Description, new { @class = "req" })
                    @Html.Raw(HttpUtility.HtmlDecode(@Html.TextBoxFor(m => m.ClaimDocuments[cnt].Description, new { maxlength = "255", required = "required" }).ToHtmlString()))
                    @Html.ValidationMessageFor(m => m.ClaimDocuments[cnt].Description)
                </div>
            </div>
            cnt++;
        }
    }
    <div style="padding: 10px 0 30px 0; width: 100%;">
        <input type="button" id="btnAddDocument" class="pure-button" style="font-size: 85%" value="Add Document" />
        <input type="button" id="btnRemoveDocument" class="pure-button" style="font-size: 85%; margin-left: 10px;" value="Remove Document" disabled="disabled" />
    </div>
    <div class="pure-g">
        <div class="pure-u-1">
            @Html.LabelFor(m => m.MissingDocumentDetails)
            @Html.TextAreaFor(m => m.MissingDocumentDetails, new { @rows = "5", @cols = "125" })
        </div>
    </div>
    <div class="k-header" style="margin-top:10px; width: 550px;">
        @Html.Hidden("UploadKey")
        <input name="files" id="files" type="file" />
    </div>
</fieldset>

TCRC/Views/Admin/_MemberStatus.cshtml
@model TCRC.Models.Admin.ProcessMemberViewModel

<fieldset>
    <legend>Member Status</legend>
    <div class="pure-g">
        <div class="pure-u-1">
            @Html.LabelFor(m => m.Notes)
            @Html.TextAreaFor(m => m.Notes, new { rows = "5", cols = "100" })
        </div>
    </div>
</fieldset>