TCRC/Models/Claim/SummaryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TCRC.Models.Claim
{
    public class SummaryViewModel
    {
        public int ClaimId { get; set; }
    }
}

TCRC/Models/FileClaim/ClaimCollateral.cs
using System;

namespace TCRC.Models.FileClaim
{
    public class ClaimCollateral
    {
        public string FileName { get; set; }
        public string FileUrl { get; set; }
        public DateTime CreateDate { get; set; }
    }
}

TCRC/Models/FileClaim/ClaimDocument.cs
using System;

namespace TCRC.Models.FileClaim
{
    public class ClaimDocument
    {
        public int ClaimDocumentId { get; set; }
        public int ClaimId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime ModifyDate { get; set; }
    }
}

TCRC/Models/FileClaim/ClaimFormViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web.Mvc;

namespace TCRC.Models.FileClaim
{
    public class ClaimFormViewModel
    {
        public ClaimFormViewModel()
        {
            ClaimPassengers = new List<ClaimPassenger>();
            ClaimPaymentProofs = new List<ClaimPaymentProof>();
            ClaimDocuments = new List<ClaimDocument>();
            ClaimHistories = new List<ClaimHistory>();
        }

        public int ClaimID { get; set; }

        public IList<ClaimHistory> ClaimHistories { get; set; }

        public byte ClaimStatusTypeId { get; set; }

        public int TcrcId { get; set; }

        [Required(ErrorMessage = "Travel Seller is required")]
        public int BusinessAddressId { get; set; }

        [Display(Name = "First Name")]
        [Required(ErrorMessage = "First Name is required")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Display(Name = "Last Name")]
        [Required(ErrorMessage = "Last Name is required")]
        public string LastName { get; set; }

        public IList<ClaimPassenger> ClaimPassengers { get; set; }

        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "City is required")]
        public string City { get; set; }

        [Required(ErrorMessage = "State is required")]
        public string State { get; set; }

        [Display(Name = "Zip Code")]
        [Required(ErrorMessage = "Zip code is required")]
        public string ZipCode { get; set; }

        public string ZipCode4 { get; set; }

        [Display(Name = "Daytime Telephone")]
        [Required(ErrorMessage = "Daytime Phone is required")]
        public string PhoneNumberPrimary { get; set; }

        [Display(Name = "Evening Phone")]
        public string PhoneNumberSecondary { get; set; }

        [Display(Name = "Email Address")]
        [DataType(DataType.EmailAddress)]
        [RegularExpression(@"^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$", ErrorMessage = "Please enter a valid Email Address!")]
        [Required(ErrorMessage = "Email Address is required")]
        [StringLength(254)]
        public string EmailAddress { get; set; }

        public static IList<SelectListItem> PaymentForms
        {
            get
            {
                IList<SelectListItem> paymentForms = new List<SelectListItem>();

                paymentForms.Add(new SelectListItem() { Text = "Cash", Value = "Cash" });
                paymentForms.Add(new SelectListItem() { Text = "Check", Value = "Check" });
                paymentForms.Add(new SelectListItem() { Text = "Credit Card", Value = "Credit Card" });
                paymentForms.Add(new SelectListItem() { Text = "Money Order", Value = "Money Order" });
                return paymentForms;
            }
        }

        public IList<ClaimPaymentProof> ClaimPaymentProofs { get; set; }

        [Required(ErrorMessage = "Description of services is required")]
        public string ScheduledServicesPurchased { get; set; }

        [Display(Name = "Scheduled Departure Date")]
        [Required(ErrorMessage = "Scheduled date of departure is required")]
        public DateTime ScheduledDepartureDate { get; set; }

        [Display(Name = "Scheduled Return Date")]
        [Required(ErrorMessage = "Scheduled return date is required")]
        public DateTime ScheduledReturnDate { get; set; }

        public string SpecificDetails { get; set; }

        [Display(Name = "TCRC Number")]
        public string TCRCNumber { get; set; }

        [Display(Name = "SOT Number")]
        public string SOTNumber { get; set; }

        [Display(Name = "Agency Name")]
        public string AgencyName { get; set; }

        [Display(Name = "City")]
        public string AgencyCity { get; set; }

        public string SellerID { get; set; }

        [Display(Name = "Total Amount of Claim")]
        [Required(ErrorMessage = "Total amount of claim is required")]
        public decimal ClaimAmountTotal { get; set; }

        [Display(Name = "Explanation of basis for claim")]
        [Required(ErrorMessage = "Explanation of basis for claim is required")]
        public string ClaimAmountBasis { get; set; }

        public IList<ClaimDocument> ClaimDocuments { get; set; }

        public Guid? UploadKey { get; set; }

        [Display(Name = "If any of the required documents are not provided, please state why below.")]
        public string MissingDocumentDetails { get; set; }

        public bool HasPurchasedInsurance { get; set; }

        [Display(Name = "Date purchased")]
        public DateTime? InsurancePurchaseDate { get; set; }

        [Display(Name = "Amount Paid")]
        public decimal? InsurancePurchaseAmount { get; set; }

        [Display(Name = "Purchased from (name and address)")]
        public string InsurancePurchasedFrom { get; set; }

        [Display(Name = "Insurer (name and address)")]
        public string Insurer { get; set; }

        public bool HasOtherReimbursement { get; set; }

        [Display(Name = "Source (name, address, phone, file or contract number)")]
        public string ReimbursementSource { get; set; }

        [Display(Name = "Details")]
        public string ReimbursementDetails { get; set; }

        public bool HasAcceptedTerms { get; set; }

        public DateTime CreateDate { get; set; }

        public DateTime ModifyDate { get; set; }

        public string Error { get; set; }
    }
}

TCRC/Models/FileClaim/ClaimHistory.cs
using System;

namespace TCRC.Models.FileClaim
{
    public class ClaimHistory
    {
        public Int16 ClaimStatusTypeId { get; set; }
        public string Notes { get; set; }
        public string EmailText { get; set; }
        public Int64 ApprovedCheckNumber { get; set; }
        public decimal ApprovedCheckAmount { get; set; }
        public DateTime ApprovedCheckDate { get; set; }
        public decimal FeeRefundAmount { get; set; }
        public Int64 ReceivedCheckNumber { get; set; }
        public decimal ReceivedCheckAmount { get; set; }
        public DateTime ReceivedCheckDate { get; set; }
        public DateTime ReceivedCheckClearedDate { get; set; }
        public DateTime ReceivedCheckBouncedDate { get; set; }
        public DateTime CreateDate { get; set; }
        public int CreateById { get; set; }
    }
}

TCRC/Models/FileClaim/ClaimPassenger.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TCRC.Models.FileClaim
{
    public class ClaimPassenger
    {
        public int ClaimPassengerId { get; set; }

        public int ClaimId { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Middle Name")]
        public string MiddleName { get; set; }

        [Display(Name = "LastName")]
        public string LastName { get; set; }

        public DateTime CreateDate { get; set; }

        public DateTime ModifyDate { get; set; }
    }
}

TCRC/Models/FileClaim/ClaimPaymentProof.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace TCRC.Models.FileClaim
{
    public class ClaimPaymentProof
    {
        public int ClaimPaymentProofId { get; set; }

        public int ClaimId { get; set; }

        [Display(Name = "Date")]
        public DateTime PaymentDate { get; set; }

        [Display(Name = "Amount")]
        public decimal PaymentAmount { get; set; }

        [Display(Name = "Form")]
        public string PaymentForm { get; set; }

        [Display(Name = "Proof will be included")]
        public bool ProofIncluded { get; set; }

        public DateTime CreateDate { get; set; }

        public DateTime ModifyDate { get; set; }
    }
}

TCRC/Models/Member/ClaimViewModel.cs
using System;

namespace TCRC.Models.Member
{
    public sealed class ClaimViewModel
    {
        public int ClaimID { get; set; }
        public DateTime CreateDate { get; set; }
        public decimal ClaimAmountTotal { get; set; }
        public string Status { get; set; }
    }
}

TCRC/Models/Member/SellerOfTravelViewModel.cs
using System;

namespace TCRC.Models.Member
{
    public sealed class SellerOfTravelViewModel
    {
        public int SotOrgId { get; set; }
        public int SotId { get; set; }
        public int TcrcId { get; set; }
        public DateTime RegExpirationDate { get; set; }
        public string SotStatus { get; set; }
        public DateTime SotApprovedDate { get; set; }
    }
}

TCRC/Controllers/FileClaimController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TCRC.BusinessLogic.Services;
using TCRC.Domain.DTOs;
using TCRC.Models;
using TCRC.Models.FileClaim;
using TCRC.Models.Member;
using AutoMapper;

namespace TCRC.Controllers
{
    public class FileClaimController : BaseController
    {
        #region Members
        private readonly IClaimService service;
        #endregion

        #region Members
        /// <summary>
        /// File claim controller constructor
        /// </summary>
        /// <param name="service">The claim service</param>
        public FileClaimController(IClaimService service)
        {
            this.service = service;
        }

        /// <summary>
        /// View claim form
        /// </summary>
        public ActionResult ClaimForm()
        {
            return View(); 
        }

        /// <summary>
        /// View add new claim
        /// </summary>
        public ActionResult AddNewClaim()
        {
            return View();
        }

        /// <summary>
        /// Submit a claim
        /// </summary>
        /// <param name="files">The uploaded files</param>
        /// <param name="model">The claim model</param>
        /// <returns>Returns the claim view model</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Submit(IEnumerable<HttpPostedFileBase> files, ClaimFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                //server side validation of business address id
                if (model.BusinessAddressId != 0)
                {
                    try
                    {
                        ClaimFormDTO claimForm = Mapper.Map<ClaimFormViewModel, ClaimFormDTO>(model);
                        service.InsertClaim(claimForm);

                        return RedirectToAction("ClaimSubmitted");
                    }
                    catch (Exception e)
                    {
                        //todo: do something with this exception
                    }
                }
                else
                {
                    ModelState.AddModelError("BusinessAddressId", "Travel Seller is required");
                }
            }
            return View("ClaimForm", model);
        }

        /// <summary>
        /// View claim submitted
        /// </summary>
        public ActionResult ClaimSubmitted()
        {
            return View();
        }

        /// <summary>
        /// Gets business addresses for claim
        /// </summary>
        /// <param name="tcrcNum">The tcrc number</param>
        /// <param name="sotNum">The sot number</param>
        /// <param name="agencyName">The agency name</param>
        /// <param name="city">The city</param>
        /// <param name="claimDateStr">The claim date</param>
        /// <param name="scheduledReturnDateStr">The scheduled return date</param>
        /// <returns>Returns business addresses partial view</returns>
        public PartialViewResult GetBusinessAddressesForClaim(int? tcrcNum, int? sotNum, string agencyName, string city, string claimDateStr, string scheduledReturnDateStr)
        {
            List<BusinessAddressDTO> addresses = service.GetBusinessAddressesForClaim(tcrcNum, sotNum, 0, agencyName, city, claimDateStr, scheduledReturnDateStr);
            List<BusinessAddress> businessAddresses = Mapper.Map<List<BusinessAddressDTO>, List<Models.Member.BusinessAddress>>(addresses);

            return PartialView("_SellerOfTravel", businessAddresses);
        }

        /// <summary>
        /// Uploads files
        /// </summary>
        /// <param name="files">The files to upload</param>
        /// <param name="uploadKey">The upload key</param>
        /// <returns>Returns the upload key</returns>
        [HttpPost]
        public ActionResult Upload(IEnumerable<HttpPostedFileBase> files, Guid? uploadKey)
        {
            if (files != null)
            {
                if (uploadKey == null)
                {
                    uploadKey = Guid.NewGuid();
                }

                var uploadPath = Server.MapPath("~/Uploads/" + uploadKey);

                if (!Directory.Exists(uploadPath))
                {
                    Directory.CreateDirectory(uploadPath);
                }

                foreach (var file in files)
                {
                    try
                    {
                        var fileName = Path.GetFileName(file.FileName);
                        var physicalPath = Path.Combine(uploadPath, fileName);
                        file.SaveAs(physicalPath);
                    }
                    catch (Exception ex)
                    {
                        //todo: do something with this exception
                    }
                }
            }

            return Json(new { data = uploadKey }, "text/plain");
        }

        /// <summary>
        /// Removes files from upload
        /// </summary>
        /// <param name="fileNames">The file names to remove</param>
        /// <param name="uploadKey">The upload key</param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Remove(string[] fileNames, Guid uploadKey)
        {
            if (fileNames != null && uploadKey != null)
            {
                var uploadPath = Server.MapPath("~/Uploads/" + uploadKey);

                foreach (var fullName in fileNames)
                {
                    try
                    {
                        var fileName = Path.GetFileName(fullName);
                        var physicalPath = Path.Combine(uploadPath, fileName);

                        if (System.IO.File.Exists(physicalPath))
                        {
                            System.IO.File.Delete(physicalPath);
                        }

                        int numFiles = Directory.GetFiles(uploadPath).Count();

                        if (numFiles == 0)
                        {
                            Directory.Delete(uploadPath);
                        }
                    }
                    catch (Exception ex)
                    {
                        //todo: do something with this exception
                    }
                }
            }

            return Content("");
        }
        #endregion
    }
}

TCRC/Views/FileClaim/AddNewClaim.cshtml
@model TCRC.Models.FileClaim.ClaimFormViewModel

<h2>Add New Claim</h2>

@using (Html.BeginForm("Submit", "FileClaim", FormMethod.Post, new { @class = "pure-form pure-form-stacked" }))
{
    @Html.AntiForgeryToken()

    Html.RenderPartial("_ClaimantInfo", Model);
    <br />
    Html.RenderPartial("_PaymentProof", Model);
    <br />
    Html.RenderPartial("_ServicesPurchased", Model);
    <br />
    Html.RenderPartial("_TravelAgency", Model);
    <br />
    Html.RenderPartial("_ClaimDetails", Model);
    <br />
    Html.RenderPartial("_Documents", Model);
    <br />
    Html.RenderPartial("_InsuranceInfo", Model);
    <br />
    Html.RenderPartial("_Reimbursement", Model);
    <br />
    Html.RenderPartial("_Waiver", Model);
    <br />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/mask")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/jquery.xfields.js")
    @Scripts.Render("~/Scripts/kendo.all.min.js")
    @Scripts.Render("~/Scripts/tcrc.claim.js")
}

TCRC/Views/FileClaim/ClaimForm.cshtml
@model TCRC.Models.FileClaim.ClaimFormViewModel

<h2>Travel Consumer Restitution Fund Claim Form</h2>
<p>
    <strong>If you are having trouble filing a claim online, you may download a claim packet by visiting the download page in the 'File A Claim' Menu.
        Complete and sign the form, then mail it to the address on the claim form along with your check for $35.00 payable to TCRC.</strong>
</p>
<h3>Special Notice to Consumers Affected by Cruise Line Closures & Reorganizations
</h3>
<p>
    The Seller of Travel Law provides that the only losses recoverable through the Travel Consumer Restitution Fund are those incurred in a transaction 
    with a registered seller of travel that is also a TCRC participant. Ocean carriers, however, are not sellers of travel as defined by Business and 
    Professions Code section 17550.1.
</p>
<p>
    For more information on filing a claim against an ocean carrier, please visit the Federal Maritime Commission’s website: 
    <a href="http://www.fmc.gov">http://www.fmc.gov</a>.
</p>
<p>
    The following steps will guide you through the File a Claim process. By California statue, 
    Section 17550.47, your claim must meet the following criteria:
</p>
<ol>
    <li>The seller of travel you have a claim against must have been a participant in the Travel Consumer Restitution Corporations (TCRC) Fund at the 
        time of sale, and the seller of travel must have been registered with the State of California, Seller of Travel Program.
    </li>
    <li>Your loss must have been more than $50.00.
    </li>
    <li>Your claim must be filed within one year after the scheduled date of completion of travel.
    </li>
</ol>
<p>
    If you paid any part of your claim with a credit card, TCRC requires that you submit proof that you have requested a charge back for all payments 
    made from the financial institution(s). @* Please refer to our Frequently Asked Questions (FAQ) titled "INFORMATION ABOUT CREDIT CARD CHARGEBACKS" 
    found on the Home page of the TCRC web site.*@
</p>
<p>
    When you complete your claim, you will need to provide (i.e. upload online) or mail in supporting documentation for your claim.
</p>

@using (Html.BeginForm("Submit", "FileClaim", FormMethod.Post, new { @class = "pure-form pure-form-stacked" }))
{
    @Html.AntiForgeryToken()

    Html.RenderPartial("_ClaimantInfo", Model);
    <br />
    Html.RenderPartial("_PaymentProof", Model);
    <br />
    Html.RenderPartial("_ServicesPurchased", Model);
    <br />
    Html.RenderPartial("_TravelAgency", Model);
    <br />
    Html.RenderPartial("_ClaimDetails", Model);
    <br />
    Html.RenderPartial("_Documents", Model);
    <br />
    Html.RenderPartial("_InsuranceInfo", Model);
    <br />
    Html.RenderPartial("_Reimbursement", Model);
    <br />
    Html.RenderPartial("_Waiver", Model);
    <br />
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/mask")
    @Scripts.Render("~/Scripts/DataTables/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/jquery.xfields.js")
    @Scripts.Render("~/Scripts/kendo.all.min.js")
    @Scripts.Render("~/Scripts/tcrc.claim.js")
}

TCRC/Views/FileClaim/ClaimSubmitted.cshtml
<h2>Claim Submitted</h2>
<p>Thank you for filing your claim with the Travel Consumer Restitution Fund.  We will contact you if further information is needed to process your claim.</p>

<p>Thank you,<br />
Travel Consumer Restitution Corporation<br />
P.O. Box 6001  <br />
Larkspur, CA 94977-6001 <br />
(866)301-3004 <br />
<a href="mailto:info@tcrcinfo.com">info@tcrcinfo.com</a> </p>

TCRC/Views/FileClaim/_ClaimDetails.cshtml
@model TCRC.Models.FileClaim.ClaimFormViewModel

<fieldset>
    <legend>Claim Details</legend>
    <p>
        STATE THE DOLLAR AMOUNT OF YOUR CLAIM AND THE BASIS FOR IT. You must state the amount of your claim in dollars 
        and specifically describe why you believe you are owed a refund in that amount by the travel seller against whom 
        your claim is made. If you are seeking reimbursement for only part of the travel services you purchased, please 
        list the specific services you did not receive and the amount of reimbursement you seek for each.
    </p>
    <div class="pure-g">
        <div class="pure-u-1">
            @Html.LabelFor(m => m.ClaimAmountTotal, new { @class = "req" })
            @Html.TextBoxFor(m => m.ClaimAmountTotal, new {@class = "money", required = "required", maxlength = "18" })
            @Html.ValidationMessageFor(m => m.ClaimAmountTotal)
        </div>
        <div class="pure-u-1">
            @Html.LabelFor(m => m.ClaimAmountBasis, new { @class = "req" })
            @Html.Raw(HttpUtility.HtmlDecode(@Html.TextAreaFor(m => m.ClaimAmountBasis, new { @rows = "5", @cols = "125", required = "required" }).ToHtmlString()))
            @Html.ValidationMessageFor(m => m.ClaimAmountBasis)
        </div>
    </div>
</fieldset>

TCRC/Views/FileClaim/_ClaimantInfo.cshtml
@model TCRC.Models.FileClaim.ClaimFormViewModel

<fieldset>
    <legend>Claimant Information</legend>
    <p>

    </p>
    <div class="pure-g">
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.FirstName, new { @class = "req" })
            @Html.TextBoxFor(m => m.FirstName, new { required = "required", maxlength = "50" })
            @Html.ValidationMessageFor(m => m.FirstName)
        </div>
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.MiddleName)
            @Html.TextBoxFor(m => m.MiddleName, new { maxlength = "50" })
        </div>
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.LastName, new { @class = "req" })
            @Html.TextBoxFor(m => m.LastName, new { required = "required", maxlength = "50" })
            @Html.ValidationMessageFor(m => m.LastName)
        </div>
        <div class="FormElementGroup" style="display: none; width: 100%;">
            <div class="pure-u-1-3">
                @Html.TextBoxFor(m => m.ClaimPassengers[0].FirstName, new { maxlength = "50" })
            </div>
            <div class="pure-u-1-3">
                @Html.TextBoxFor(m => m.ClaimPassengers[0].MiddleName, new { maxlength = "50" })
            </div>
            <div class="pure-u-1-3">
                @Html.TextBoxFor(m => m.ClaimPassengers[0].LastName, new { maxlength = "50" })
            </div>
        </div>
        <div class="pure-u-1" style="padding: 10px 0 30px 0;">
            <input type="button" id="btnAddPassenger" class="pure-button" style="font-size: 85%;" value="Add Passenger" />
            <input type="button" id="btnRemovePassenger" class="pure-button" style="font-size: 85%; margin-left: 10px;" value="Remove Passenger" disabled="disabled" />
        </div>
        <div class="pure-u-1-1">
            @Html.LabelFor(m => m.Address, new { @class = "req" })
            @Html.TextBoxFor(m => m.Address, new { @class = "pure-input-2-3", required = "required", maxlength = "255" })
            @Html.ValidationMessageFor(m => m.Address)
        </div>
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.City, new { @class = "req" })
            @Html.TextBoxFor(m => m.City, new { required = "required", maxlength = "50" })
            @Html.ValidationMessageFor(m => m.City)
        </div>
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.State, new { @class = "req" })
            @Html.DropDownListFor(m => m.State, new ListOfStates(), new { @class = "pure-u-11-12", required = "required" })
            @Html.ValidationMessageFor(m => m.State)
        </div>
        <div class="pure-u-1-12">
            @Html.LabelFor(m => m.ZipCode, new { @class = "req" })
            @Html.TextBoxFor(m => m.ZipCode, new { @class = "pure-input-1", mask = "99999", maxlength = "5", required = "required" })
            @Html.ValidationMessageFor(m => m.ZipCode)
        </div>
        <div class="pure-u-1-24" style="text-align: center;">
            <label>&nbsp;</label>
            -
        </div>
        <div class="pure-u-4-24">
            <label>&nbsp;</label>
            @Html.TextBoxFor(m => m.ZipCode4, new { @class = "pure-input-1-3", mask = "9999", maxlength = "4" })
        </div>
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.PhoneNumberPrimary, new { @class = "req" })
            @Html.TextBoxFor(m => m.PhoneNumberPrimary, new { mask = "(999) 999-9999", required = "required" })
            @Html.ValidationMessageFor(m => m.PhoneNumberPrimary)
        </div>
        <div class="pure-u-2-3">
            @Html.LabelFor(m => m.PhoneNumberSecondary)
            @Html.TextBoxFor(m => m.PhoneNumberSecondary, new { mask = "(999) 999-9999" })
        </div>
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.EmailAddress, new { @class = "req" })
            @Html.TextBoxFor(m => m.EmailAddress, new { @class = "pure-input-1", maxlength = "255", required = "required" })
            @Html.ValidationMessageFor(m => m.EmailAddress)
        </div>
    </div>
</fieldset>

TCRC/Views/FileClaim/_Documents.cshtml
@model TCRC.Models.FileClaim.ClaimFormViewModel

<fieldset>
    <legend>Documents</legend>
    <p>
        You must provide a copy of those documents that set forth the travel services purchased, such as airline tickets, itinerary, 
        invoice or other agreements that support your claim. Input the title of the document and a description of its contents.
    </p>
    <div class="pure-g FormElementGroupDocuments">
        <div class="pure-u-1-3">
            @Html.LabelFor(m => m.ClaimDocuments[0].Name, new { @class = "req" })
            @Html.TextBoxFor(m => m.ClaimDocuments[0].Name, new { maxlength = "100", required = "required" })
            @Html.ValidationMessageFor(m => m.ClaimDocuments[0].Name)
        </div>
        <div class="pure-u-2-3">
            @Html.LabelFor(m => m.ClaimDocuments[0].Description, new { @class = "req" })
            @Html.TextBoxFor(m => m.ClaimDocuments[0].Description, new { maxlength = "255", required = "required" })
            @Html.ValidationMessageFor(m => m.ClaimDocuments[0].Description)
        </div>
    </div>
    <div style="padding: 10px 0 30px 0; width: 100%;">
        <input type="button" id="btnAddDocument" class="pure-button" style="font-size: 85%" value="Add Document" />
        <input type="button" id="btnRemoveDocument" class="pure-button" style="font-size: 85%; margin-left: 10px;" value="Remove Document" disabled="disabled" />
    </div>
    <div class="pure-g">
        <div class="pure-u-1">
            @Html.LabelFor(m => m.MissingDocumentDetails)
            @Html.TextAreaFor(m => m.MissingDocumentDetails, new { @rows = "5", @cols = "125" })
        </div>
    </div>
    <div class="k-header" style="margin-top:10px; width: 550px;">
        @Html.Hidden("UploadKey")
        <input name="files" id="files" type="file" />
    </div>
</fieldset>

TCRC/Views/FileClaim/_Waiver.cshtml
@model TCRC.Models.FileClaim.ClaimFormViewModel

<div class="">
    <p>
        NOTICE OF WAIVER: BY FILING A CLAIM WITH THE TCRC, YOU WAIVE THE RIGHT TO BRING ANY ACTION AT LAW OR EQUITY, 
        INCLUDING A SMALL CLAIMS COURT ACTION, THAT IS AGAINST THE SAME SELLER OF TRAVEL AND THAT ARISES FROM THE 
        TRANSACTION THAT IS THE SUBJECT OF THIS CLAIM. See the enclosed instructions and waiver form for further details. 
        I/WE DECLARE UNDER PENALTY OF PERJURY UNDER THE LAWS OF THE STATE OF CALIFORNIA THAT THE INFORMATION PROVIDED 
        IN THIS CLAIM IS TRUE AND CORRECT.
    </p>
    <div style="text-align: center">
        @Html.CheckBoxFor(m => m.HasAcceptedTerms) Accept Terms
        <br /><br />
        <input type="submit" id="btnSubmit" class="pure-button pure-button-primary" value="Submit" disabled="disabled" />
    </div>
</div>